version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: corelabdb
    ports:
      - 5432:5432
  adonis_app:
    container_name: adonis_app
    restart: always
    depends_on:
      - postgres
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
      - 9229:9229 # for debug
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    command: node ace serve --watch --node-args="--inspect=0.0.0.0"
